openapi: 3.0.0
info:
  title: OdinEye API
  description: OdinEye API Specification
  version: v1
servers:
  - url: http://localhost:2469
tags:
  - name: server
    description: Server related resources
    x-displayName: Server

paths:
  /serverDetails:
    get:
      tags:
        - server
      summary: Retrieve game server info
      description: Returns general game server information.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerDetails'

components:
  schemas:
    ServerDetails:
      properties:
        MaxNumberOfPlayers:
          type: integer
          description: Maximum number of players permitted on the server.
          format: int32
          minimum: 1
          example: 10
        GameVersion:
          description: Version of the game server.
          type: string
          minLength: 1
          example: 0.220.2
        SteamAppId:
          description: Steam application identifier of the game server.
          type: string
          minLength: 1
          example: "892970"
